const express = require('express');

const sequoiaRoomSeeds = [
    {
        building: "Sequoia",
        floor: 1,
        roomNumber: 1,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Sequoia",
        floor: 1,
        roomNumber: 2,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Sequoia",
        floor: 1,
        roomNumber: 3,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Sequoia",
        floor: 1,
        roomNumber: 4,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Sequoia",
        floor: 1,
        roomNumber: 5,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Sequoia",
        floor: 1,
        roomNumber: 6,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
];

module.exports = sequoiaRoomSeeds;