const express = require('express');

const lakesideRoomSeeds = [
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 510,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 512,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 514,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 516,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 520,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 521,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 522,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 523,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 524,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 525,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 526,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 527,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 530,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 531,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 532,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 533,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 534,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 535,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 536,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 5,
        roomNumber: 537,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 610,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 612,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 614,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 616,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 620,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: true,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 621,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: true,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 622,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 623,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 624,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 625,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 626,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 627,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 630,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 631,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 632,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 633,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 634,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 635,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 636,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 6,
        roomNumber: 637,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 710,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 712,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 714,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 716,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 720,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 721,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 722,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 723,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 724,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 725,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 726,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 727,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 730,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 731,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 732,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 733,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 734,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 735,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 736,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
    {
        building: "Lakeside",
        floor: 7,
        roomNumber: 737,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
        ada: false,
    },
]

module.exports = lakesideRoomSeeds;