const express = require('express');

const seedRooms = [
    {
        building: "Lakeside",
        floor: 1,
        roomNumber: 510,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 1,
        roomNumber: 512,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 1,
        roomNumber: 514,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 1,
        roomNumber: 516,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 520,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 521,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 522,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 523,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 524,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 525,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 526,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
    },
    {
        building: "Lakeside",
        floor: 2,
        roomNumber: 527,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 530,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 531,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 532,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 533,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 534,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 535,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 536,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: true,
    },
    {
        building: "Lakeside",
        floor: 3,
        roomNumber: 537,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
    },
]

module.exports = seedRooms;