const express = require('express');

const birchRoomSeeds = [
    {
        building: "Birch",
        floor: 1,
        roomNumber: 10,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 1,
        roomNumber: 11,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 1,
        roomNumber: 12,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 1,
        roomNumber: 13,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 1,
        roomNumber: 14,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 2,
        roomNumber: 20,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 2,
        roomNumber: 21,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 2,
        roomNumber: 22,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 2,
        roomNumber: 23,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Birch",
        floor: 2,
        roomNumber: 24,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
];

module.exports = birchRoomSeeds;