const express = require('express');

const gwinnRoomSeeds = [
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 10,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 11,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 12,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 13,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 14,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 15,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 16,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 17,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 18,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 19,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 20,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 21,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 22,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 23,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 24,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 25,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 26,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 27,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 28,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
    {
        building: "Gwinn",
        floor: 1,
        roomNumber: 29,
        assignedTo: [],
        status: "Clean",
        amenities: "C, R, M",
        masterDeluxe: false,
        ada: false,
    },
];

module.exports = gwinnRoomSeeds;